EcalTiming: EcalCrystalTimingCalibration Class Reference
EcalCrystalTimingCalibration Class Reference
#include <EcalCrystalTimingCalibration.h>
Public Member Functions
EcalCrystalTimingCalibration (bool weightMean=true)
default constructor
unsigned int num () const
float mean () const
float stdDev () const
average time (mean of the time distribution)
float meanError () const
bool add (EcalTimingEvent te_)
add new event for this crystal
Friends
ostream & operator<< (ostream &os, const EcalCrystalTimingCalibration &s)
Detailed Description
Description: add a description here This class contains all the timing information for a single crystal
Constructor & Destructor Documentation
EcalCrystalTimingCalibration::EcalCrystalTimingCalibration (bool weightMean = true) inline
default constructor
Member Function Documentation
bool EcalCrystalTimingCalibration::add (EcalTimingEvent te_) inline
add new event for this crystal
float EcalCrystalTimingCalibration::mean () const inline
Referenced by stdDev().
float EcalCrystalTimingCalibration::meanError () const inline
References stdDev().
unsigned int EcalCrystalTimingCalibration::num () const inline
float EcalCrystalTimingCalibration::stdDev () const inline
average time (mean of the time distribution)
< standard deviation of the time distribution
References mean().
Referenced by meanError().
Friends And Related Function Documentation
ostream& operator<< (ostream & os, const EcalCrystalTimingCalibration & s) friend
The documentation for this class was generated from the following file:
interface/EcalCrystalTimingCalibration.h